// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEwSEdXdGp3c3Ut1XcVYpHhw6IeK2duuw',
    appId: '1:15134422794:web:00f7b37613a1fc1798ecf3',
    messagingSenderId: '15134422794',
    projectId: 'mynotes-chocho',
    authDomain: 'mynotes-chocho.firebaseapp.com',
    storageBucket: 'mynotes-chocho.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYleS_f3GluTRu1aq0Xneay7xthVdo49s',
    appId: '1:15134422794:android:8fd6821f41aa80b998ecf3',
    messagingSenderId: '15134422794',
    projectId: 'mynotes-chocho',
    storageBucket: 'mynotes-chocho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Iru9I_09AaUQnNjGva4LGNItMk6T9_c',
    appId: '1:15134422794:ios:9ce3bdae7796077598ecf3',
    messagingSenderId: '15134422794',
    projectId: 'mynotes-chocho',
    storageBucket: 'mynotes-chocho.appspot.com',
    iosClientId: '15134422794-45ub1vdeu4nqbq7bq7fiiu240jbsvao9.apps.googleusercontent.com',
    iosBundleId: 'eu.chochosan.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Iru9I_09AaUQnNjGva4LGNItMk6T9_c',
    appId: '1:15134422794:ios:9ce3bdae7796077598ecf3',
    messagingSenderId: '15134422794',
    projectId: 'mynotes-chocho',
    storageBucket: 'mynotes-chocho.appspot.com',
    iosClientId: '15134422794-45ub1vdeu4nqbq7bq7fiiu240jbsvao9.apps.googleusercontent.com',
    iosBundleId: 'eu.chochosan.mynotes',
  );
}
